<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Администрация г. Красноярска' => 'Krasnoyarsk City Administration',
    'Администрация города' => 'City Administration',
    'Администрация города Красноярск' => '',
    'Адрес' => 'Address',
    'Версия для слабовидящих' => 'For visually impaired',
    'Красноярск' => 'Krasnoyarsk',
    'Обратная связь' => 'Feedback',
    'Обычная версия сайта' => '',
    'Поиск по сайту' => 'Search',
    'Сайт администрации города' => '',
    'Телефон/факс' => 'Telephone/Fax',
    'Показать новости за период' => 'Show news for period',
    'Рубрика' => 'Rubric',
    'Все рубрики' => 'All rubrics',
    'Дополнительная информация для СМИ' => 'Press info',
    'Похожие новости' => 'Similar news',
    'Дата публикации (изменения)' => 'Publish (changing) date',
    'Просмотров за год (всего)' => 'Total (annual) views',
    'Поделиться' => 'Share',
    'Распечатать' => 'Print'
];
