<?php

namespace common\components\smevsoap;

class ClientIdCriteria
{
    const __default = 'GET_REQUEST_BY_REQUEST_CLIENTID';
    const GET_REQUEST_BY_REQUEST_CLIENTID = 'GET_REQUEST_BY_REQUEST_CLIENTID';
    const GET_RESPONSE_BY_REQUEST_CLIENTID = 'GET_RESPONSE_BY_REQUEST_CLIENTID';
    const GET_RESPONSE_BY_RESPONSE_CLIENTID = 'GET_RESPONSE_BY_RESPONSE_CLIENTID';


}
