<?php

namespace frontend\modules\api\models;

use Yii;

class Collection extends \common\models\Collection
{
    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }
}
